apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fluffy-acme
spec:
  acme:
    server: 'xxx'
    email: 'xxx'
    privateKeySecretRef:
      name:'xxx'

    # Le indica a cert-manager que confíe en la conexión HTTPS con el servidor Step-CA
    skipTLSVerify: true

    solvers:
    - http01:
        ingress:
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: traefik
